spring.application.name=Circuit_breaker_Resillence


resilience4j.retry.instances.retryApi.maxAttempts=3
resilience4j.retry.instances.retryApi.waitDuration=2s
resilience4j.retry.metrics.enabled=true
resilience4j.retry.metrics.legacy.enabled=true

