spring.application.name=Circuit_breaker_Resillence


resilience4j.retry.instances.retryApi.maxAttempts=3
resilience4j.retry.instances.retryApi.waitDuration=2s
resilience4j.retry.metrics.enabled=true
resilience4j.retry.metrics.legacy.enabled=true

management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.instances.circuitBreakerDemo.register-health-indicator=true
resilience4j.circuitbreaker.instances.circuitBreakerDemo.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.circuitBreakerDemo.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.circuitBreakerDemo.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.circuitBreakerDemo.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.circuitBreakerDemo.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.circuitBreakerDemo.sliding-window-size=10
resilience4j.circuitbreaker.instances.circuitBreakerDemo.sliding-window-type=count-based

management.endpoints.web.exposure.include=*
