spring.application.name=jpa-demo

spring.datasource.url=jdbc:mysql://localhost:3306/bhaskar
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.primary.url=jdbc:mysql://localhost:3306/bhaskar
#spring.datasource.primary.username=springstudent
#spring.datasource.primary.password=springstudent
#spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.datasource.secondary.url=jdbc:mysql://localhost:3306/foodcatelog
#spring.datasource.secondary.username=root
#spring.datasource.secondary.password=bhaskar
#spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA settings (applies to primary datasource by default)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true