version: "3.8"

services:
  patient-service:
    image : patient
    container_name: patient-container
    ports:
      - '8080:8080'

  doctor-service:
    image: doctor
    container_name: doctor-container
    ports:
      - '8081:8080'